version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run :
          name: Install flask
          command: 
            pip install flask
      - run : 
          name: compile python app
          command: 
            python3 app.py
  deploy:
    docker:
      - image: cimg/base:2021.10
    steps:
      - checkout
      - run :
          name: Install python dependencies
          command: |
            sudo apt update 
            sudo apt install python3 
            sudo apt install python3-flask 
            flask --version
      - run :
          name: Connect to ec2 instance
          command: |
            echo Start deploy
            ssh -o StrictHostKeyChecking=no ubuntu@18.208.169.102 git@github.com:aswin219/flaskapp-aws.git app sudo nohup python3 app/app.py > log.txt 2>&1 &
              
            
workflows:
  mybuild:
    jobs:
      - build
      - deploy:
          requires:
            - build



